version: '3.4'

x-server-tmpl: &server-tmpl
  environment:
    DEBUG: 'True'
    CELERY_BROKER: 'amqp://guest:guest@rabbitmq:5672/'
    DB_NAME: 'new_base'
    DB_HOST: 'db'
    BROKER_URL: 'amqp://user:password@rabbitmq:5672/my_vhost'
    MYSQL_ROOT_PASSWORD: 'root'
    MYSQL_DATABASE: 'new_base'

services:
    nginx:
      restart: always
      build:
        context: ./
        dockerfile: ./nginx/Dockerfile
      depends_on:
        - server
      ports:
        - 80:80

    server:
      build:
        context: ./
        dockerfile: server/Dockerfile
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./server:/server/
        - ./log:/server/log/
      ports:
        - "8000:8000"
      depends_on:
        - db
        - celery
        - redis
      <<: *server-tmpl
    rabbitmq:
        image: rabbitmq:3.7.5
        hostname: rabbitmq
        ports:
          - 5672:5672
        expose:
          - 5672
        environment:
          RABBITMQ_DEFAULT_USER: 'user'
          RABBITMQ_DEFAULT_PASS: 'password'
          RABBITMQ_DEFAULT_VHOST: 'my_vhost'
    db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: new_base
      ports:
        - 3308:3306
    redis:
      image: redis:5.0.5
      ports:
        - 6379:6379

    celery:
      build:
        context: ./
        dockerfile: server/Dockerfile
      command:  celery worker -A config -B -l info -Q default,celery -s /var/run/celerybeat-schedule
      volumes:
        - ./server:/server/
      depends_on:
        - db
        - redis
        - rabbitmq
      <<: *server-tmpl
