# Generated by Django 2.2.8 on 2020-04-12 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_url', models.URLField()),
                ('sub_part', models.CharField(max_length=8, verbose_name='Sub part')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.Session', verbose_name='Session')),
            ],
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['sub_part'], name='shortener_s_sub_par_35d124_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['redirect_url'], name='shortener_s_redirec_da7ae6_idx'),
        ),
    ]
